version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hyf-adwi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hyf-adwiseli-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - hyf-adwi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d hyf-adwiseli-db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: hyf-adwi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hyf-adwi-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  hyf-adwi-network:
    driver: bridge 